### ISSUE TITLE
Default "tostring" operator

### ISSUE THREAD

**Issue by MikuAuahDark** [ImagicTheCat/Luaoop#3]
It would be good to have default "tostring" operator instead of forcing user implement it by itself. Example scenario where this useful is for debugging purpose where someone just wants to do simple `print(objectInstance)`.

**Comment by ImagicTheCat** [comment]
If you speak about the Lua default tostring behavior: difficult to implement since there is no `rawtostring` available, modifying the metatable is not always possible (cclass). And the default function only display the table address, which is not really useful in most debug cases. 

If you speak about creating a new default tostring behavior, I think it's hard to find something that will please everyone. It could print all direct properties of the object, but then output formatting is required and can't really be done nicely because each property can implement it's own tostring formatting, breaking the flow. I think it's better to use something like `print(inspect(object))` that will not use `tostring` at all for debugging. An object containing objects should know how to print itself and print them properly, be forced to implement `tostring` seems fine.

However, you can derivate all your objects from an `Object` class if you need default behaviors on your objects. Methods are cached so there is no loss of performance with inheritance (that I know of).

**Comment by MikuAuahDark** [comment]
Actually, default tostring operator for instance which just prints "instance of <classname>" is actually better than nothing (and throw Lua error).

**Comment by ImagicTheCat** [comment]
I see, I added something similar to what Lua do with tables. https://github.com/ImagicTheCat/Luaoop/commit/c343aa8ac857f18e079127eec910b9a56461bf4c
`(c)class<type>: instance id`
